server:
  port: 8081
  error:
    include-message: always

data:
  mongodb:
    database: morax
    uri: mongodb://root:password@localhost:27017/admin
    table:
      user: user
      token: token
      locations: locations
      artifacts: artifacts
      events: events
      quizzes: quizzes


spring:
  data:
    mongodb:
      auto-index-creation: true
      database: morax
      uri: mongodb://root:password@localhost:27017/admin

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

logging:
  level:
    org.springframework.security: TRACE


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha